name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: real
            theme: "idée test"
            dummy: false
          - id: dummy
            theme: "dummy ci"
            dummy: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ "${{ matrix.dummy }}" = "true" ]; then
            python -m core.run_pipeline --theme "${{ matrix.theme }}" --dummy
          else
            python -m core.run_pipeline --theme "${{ matrix.theme }}"
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-${{ matrix.id }}
          path: out/
